### ISSUE TITLE
Issue with "Wet Bulb Temperature, Hourly"

### ISSUE THREAD

**Issue by clarence-chew** [datagovsg/datagovsg-datasets#1049]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Wet Bulb Temperature, Hourly

### If there's an issue with a dataset, please provide a description of the problem
There are 23 rows under 1986-04-13 and 25 rows under 1986-04-14. All hours should be labelled 1 to 24, however, hour 24 of 1986-04-13 has been labelled as hour 0 of 1986-04-14.

Here are the rows around the issue.
1986-04-12,1,25.1
1986-04-12,2,24.8
1986-04-12,3,24.3
1986-04-12,4,23.5
1986-04-12,5,23.5
1986-04-12,6,23.7
1986-04-12,7,23.8
1986-04-12,8,23.9
1986-04-12,9,24.4
1986-04-12,10,25.4
1986-04-12,11,26
1986-04-12,12,26
1986-04-12,13,26
1986-04-12,14,26.8
1986-04-12,15,26.7
1986-04-12,16,26.4
1986-04-12,17,25.5
1986-04-12,18,25.5
1986-04-12,19,25.4
1986-04-12,20,25.5
1986-04-12,21,25.5
1986-04-12,22,25.8
1986-04-12,23,25.8
1986-04-12,24,26
1986-04-13,1,26
1986-04-13,2,25.5
1986-04-13,3,25.6
1986-04-13,4,25.5
1986-04-13,5,25.1
1986-04-13,6,24.8
1986-04-13,7,24.9
1986-04-13,8,25.5
1986-04-13,9,26.2
1986-04-13,10,26.4
1986-04-13,11,26.5
1986-04-13,12,25
1986-04-13,13,24.1
1986-04-13,14,23.8
1986-04-13,15,24.3
1986-04-13,16,24.1
1986-04-13,17,24.5
1986-04-13,18,24.8
1986-04-13,19,24.6
1986-04-13,20,24.5
1986-04-13,21,24.4
1986-04-13,22,24.4
1986-04-13,23,24.5
1986-04-14,0,24.6 **this row**
1986-04-14,1,24.6
1986-04-14,2,24.5
1986-04-14,3,24.3
1986-04-14,4,24.2
1986-04-14,5,24.1
1986-04-14,6,23.9
1986-04-14,7,23.9
1986-04-14,8,25
1986-04-14,9,26.2
1986-04-14,10,26
1986-04-14,11,25.9
1986-04-14,12,25.5
1986-04-14,13,25.5
1986-04-14,14,25.6
1986-04-14,15,25.5
1986-04-14,16,24.8
1986-04-14,17,25
1986-04-14,18,25
1986-04-14,19,25.2
1986-04-14,20,25
1986-04-14,21,25.1
1986-04-14,22,25.5
1986-04-14,23,25.4
1986-04-14,24,25.4
1986-04-15,1,25.5
1986-04-15,2,25.5
1986-04-15,3,25.1
1986-04-15,4,25
1986-04-15,5,25
1986-04-15,6,24.8
1986-04-15,7,24.6
1986-04-15,8,25.2
1986-04-15,9,25.7
1986-04-15,10,26
1986-04-15,11,27
1986-04-15,12,26.1
1986-04-15,13,26.5
1986-04-15,14,26.5
1986-04-15,15,26.2
1986-04-15,16,25.8
1986-04-15,17,25.1
1986-04-15,18,25.1
1986-04-15,19,25.2
1986-04-15,20,25.3
1986-04-15,21,25.6
1986-04-15,22,25.6
1986-04-15,23,25.4
1986-04-15,24,25.4

**Comment by lennardl** [comment]
@clarence-chew I've been informed that the error has been fixed.

**Comment by clarence-chew** [comment]
I see that it is last updated at April 14, 2021, 09:32 (SGT) on the https://data.gov.sg/dataset/wet-bulb-temperature-hourly website, but the data formatting issue still persists.

**Comment by lennardl** [comment]
@clarence-chew thanks for the feedback, I've informed the data owners on this. On the data formatting issue was it the same field or new fields?

**Comment by clarence-chew** [comment]
The fields affected are the date and hour field.
